### ISSUE TITLE
Sync JavaScriptKit runtime library with Package.resolved

### ISSUE THREAD

**Issue by kateinoigakukun** [swiftwasm/carton#155]
AFAIU, carton supports only one version of JavaScriptKit runtime library now. If carton can dynamically determine the JavaScriptKit runtime library version based on Package.resolved and embed it, it would be really helpful.

**Comment by MaxDesiatov** [comment]
I guess this is somewhat related to #120. If we use libSwiftPM for package models, we'd also get `Package.resolved` parsing capabilities too...

**Comment by MaxDesiatov** [comment]
This should probably be superseded by https://github.com/swiftwasm/carton/issues/175, when JavaScriptKit runtime is shipped as a SwiftPM resource.
