### ISSUE TITLE
Use `SerializedDiagnostics` for diagnostics parsing

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#181]
This is already implemented in [the latest stable version of TSC](https://github.com/apple/swift-tools-support-core/blob/aab25103fa74f00ee4dc651c723f05b946395037/Sources/TSCUtility/SerializedDiagnostics.swift#L13). Required output files can be emitted by passing ` -Xswiftc -serialize-diagnostics` to `swift build`. This will allow us to keep the output of `swift build` untouched during the build process, thus preserving the build progress. Build progress output is currently absent, but was available before our own diagnostic parsing from `swift build` stdout was introduced.

**Comment by kateinoigakukun** [comment]
Build error diagnostics is now delegated to SwiftPM
