### ISSUE TITLE
Replace hard-coded path delimiters

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [swiftwasm/carton#183]
I noticed on [line 178 of Toolchain.swift](https://github.com/swiftwasm/carton/blob/09a4e67e9efa218d6e07ee10c664949a0b039da7/Sources/SwiftToolchain/Toolchain.swift#L178), there is a hard-coded path delimiter `/`. Other places in the code base might be using hard-coded path delimiters too, but I didn't check. In my opinion, they are bad for cross-platform compatibility (at least with Windows and many other DOS-descendents). It's probably better to replace them with [`URL.appendingPathComponent(_:)`](https://developer.apple.com/documentation/foundation/url/1780239-appendingpathcomponent), [`TSCBasic.AbsolutePath.appending(component:)`](https://github.com/apple/swift-tools-support-core/blob/3ae103eca680199224b6ab335db6a8ae3ecb43a3/Sources/TSCBasic/Path.swift#L151), or [`TSCBasic.AbsolutePath.appending(components:)`](https://github.com/apple/swift-tools-support-core/blob/3ae103eca680199224b6ab335db6a8ae3ecb43a3/Sources/TSCBasic/Path.swift#L160).

I think this is a good "beginner bug" if anyone is looking for one to work on.

**Comment by aswathytsbeo** [comment]
Path.Combine(path, "SearchLog") + "\\" + FolderByYearWise + "\\" + FileID
to remove this hard coded path delimiter in sonar lint
