### ISSUE TITLE
Add support for Amazon Linux 2

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#222]
Now that [recent snapshots](https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2021-02-14-a) support Amazon Linux 2, `carton` commands should be able to detect it and install an appropriate distribution archive.

**Comment by kateinoigakukun** [comment]
Closed by https://github.com/swiftwasm/carton/pull/397
