### ISSUE TITLE
`carton test` command unable to find gtk+3 using `--template tokamak`

### ISSUE THREAD

**Issue by tillhainbach** [swiftwasm/carton#241]
### Problem

Running `carton test` fails on `compiling...`with:
```sh
Process failed and produced following output:
warning: you may be able to install gdk-3.0 using your system-packager:
    brew install gtk+3

warning: you may be able to install gtk+-3.0 using your system-packager:
    brew install gtk+3


Error: warning: you may be able to install gdk-3.0 using your system-packager:
    brew install gtk+3

warning: you may be able to install gtk+-3.0 using your system-packager:
    brew install gtk+3
``` 

running the test suite from within Xcode works just fine (though the test suite is failing, maybe related to #212)

### Expected Behaviour

test suite should compile on run (and then either failure or succeed). 

### Steps-to-reproduce
following the official docs @ [Tokamak repo](https://github.com/TokamakUI/Tokamak#getting-started)
```sh
$ mkdir TokamakApp && cd TokamakApp
$ carton init --template tokamak
$ carton test
```

### System Specs

- macOS 11.3.1
- carton 0.9.1
- gtk+3 3.24.29 (via HomeBrew)

pkg-config does find gtk+-3.0 (validated with `pkg-config --libs gtk+-3.0` and ` pkg-config --cflags gtk+-3.0`)

**Comment by MaxDesiatov** [comment]
Thanks for reporting this. It should be fixed in the `main` branch and the imminent 0.10.0 release of `carton`.
