### ISSUE TITLE
Docker tag for 0.10.0?

### ISSUE THREAD

**Issue by SDGGiesbrecht** [swiftwasm/carton#246]
0.10.0 doesn’t seem to have a corresponding Docker tag. See [here](ghcr.io/swiftwasm/carton). Is this deliberate or an oversight?

**Comment by MaxDesiatov** [comment]
Sorry, this was an oversight, but an image for 0.11 is now available. Would you still need an image for 0.10 for any purpose?

**Comment by SDGGiesbrecht** [comment]
No, I have already moved to 0.11.

**Comment by SDGGiesbrecht** [comment]
[Same thing now with `0.12.0`.](https://github.com/swiftwasm/carton/pkgs/container/carton) (Although it is still so fresh this time that maybe it just takes a while to show up?)

**Comment by MaxDesiatov** [comment]
For some reason Docker release job [failed](https://github.com/swiftwasm/carton/runs/4342663102?check_suite_focus=true), probably because of [recent GitHub incident](https://www.githubstatus.com/history)

**Comment by MaxDesiatov** [comment]
That one's failing too, not sure why. Also now I remember I need the parent `swiftwasm` 5.5 to be updated too, that's running right now here https://github.com/swiftwasm/swiftwasm-docker/actions/runs/1513668833

**Comment by SDGGiesbrecht** [comment]
`swiftwasm` looks fine now, but `carton`’s latest attempt still seems to have [failed](https://github.com/swiftwasm/carton/runs/4347255788?check_suite_focus=true).

**Comment by MaxDesiatov** [comment]
Thanks, I'm aware of that. I can't build an x86_64 image manually, as I currently only have access to M1 hardware. Will need some time to get that GHA workflow investigated and fixed.

**Comment by MaxDesiatov** [comment]
An image for `carton` 0.12.1 is now available on GHCR.

**Comment by SDGGiesbrecht** [comment]
Thanks for the notification! 👍
