### ISSUE TITLE
Demo cannot be run on Safari 14

### ISSUE THREAD

**Issue by carson-katri** [swiftwasm/carton#25]
Everytime I get the `Unhandled Promise Rejection: TypeError: Conversion from 'BigInt' to 'number' is not allowed.` error due to `print` I believe.

**Comment by MaxDesiatov** [comment]
We use `0.10.2` WASI polyfill in Safari, but I don't think anything changed there with regards to BigInt in the recent versions, need to verify it though.

**Comment by MaxDesiatov** [comment]
PR submitted to the WASI polyfill code as https://github.com/wasmerio/wasmer-js/pull/231.
