### ISSUE TITLE
Backtraces demangling

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#26]
In absence of proper debugging support in browsers it's very hard to debug things where there's no backtrace whatsoever, even for array out of bounds errors.

We need to investigate whether supporting [`swift-backtrace`](https://github.com/swift-server/swift-backtrace/) is viable.

**Comment by MaxDesiatov** [comment]
`swift-backtrace` won't work, neither WebAssembly nor WASI support the required low-level code to my knowledge. The host environment is supposed to provide the backtraces, and it actually [does so in browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/RuntimeError). Thus, the question is more about demangling the backtraces. I don't think there's an existing Swift demangling implementation in JavaScript to use in the `dev.js` entrypoint, and it seems not that easy to pull the actual runtime implementation from the [`swiftDemangling` library](https://github.com/apple/swift/tree/master/lib/Demangling). A stopgap solution could be the [CwlDemangle](https://github.com/mattgallagher/CwlDemangle) package, but seems like that requires `Foundation`.

**Comment by kateinoigakukun** [comment]
I think you can use `swift_demangle` function defined in stdlib as same as wasminspect does. https://github.com/kateinoigakukun/wasminspect/blob/master/crates/swift-runtime/src/lib.rs

**Comment by MaxDesiatov** [comment]
Yes, thanks for pointing me to it. I'm also thinking we don't necessarily have to demangle in the browser, an error with its backtrace can be sent to `carton` via the WebSocket connection that's already there for hot reloads, then `carton` can print the demangled backtrace in its own output. Also much more convenient for jumping to files and lines mentioned in the backtrace if you have `carton` open in your IDE console.

**Comment by MaxDesiatov** [comment]
This was fully resolved in #186.
