### ISSUE TITLE
Carton 0.12.0 with SwiftWasm 5.5.0 fails with linker command

### ISSUE THREAD

**Issue by Sefford** [swiftwasm/carton#268]
Hello, I have been running Carton 0.12.0 with SwiftWasm and my build fails with the linker command in https://github.com/swiftwasm/swift/issues/3891.

I have checked the PR on https://github.com/swiftwasm/carton/pull/263 indicating you had added the required linker flags in carton; but looking at the code in 

https://github.com/swiftwasm/carton/blob/04de1c22296efe925cc002b3245613faacd26162/Sources/SwiftToolchain/Toolchain.swift#L258

and 

https://github.com/swiftwasm/carton/blob/04de1c22296efe925cc002b3245613faacd26162/Sources/SwiftToolchain/Toolchain.swift#L307

I believe you have only added them for `carton test` and not `carton build` command? Would that be correct?

Is there a way to manually input those flags via command line?

Thanks!

**Comment by MaxDesiatov** [comment]
Thanks! As a temporary workaround you could check the `swift build` command `carton dev --verbose` emits in console output.

What kind of error message are you seeing by the way? This will help me investigate the issue and fix it properly.

**Comment by Sefford** [comment]
Sure! 

The command. I see is

`swift build -c debug --product BrowserApp --triple wasm32-unknown-wasi -Xlinker /Users/<username>/.carton/static/so_sanitizer.wasm -Xlinker --stack-first`

and the error is the same as I mentioned earlier, the same as https://github.com/swiftwasm/swift/issues/3891.

```
<goes like this>
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_trans_64
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_close_64
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_openU_64
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_openU_64
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_openU_64
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_openU_64
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_close_64
wasm-ld: error: /Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/lib/swift_static/wasi/libFoundation.a(CFStringTransform.c.obj): undefined symbol: utrans_close_64
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

I have noticed also the command output by carton when doing `carton bundle` is 

`/Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/bin/swift build -c release --product BrowserApp --triple wasm32-unknown-wasi`

while in `carton test` is 

`/Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/bin/swift build -c debug --product CrossplatformPackageTests --triple wasm32-unknown-wasi -Xswiftc -color-diagnostics -Xlinker -licuuc -Xlinker -licui18n`

which would match what I saw browsing the source code in https://github.com/swiftwasm/carton/blob/04de1c22296efe925cc002b3245613faacd26162/Sources/SwiftToolchain/Toolchain.swift

However, if I manually execute the command `carton bundle` generates

`swift build -c release --product BrowserApp --triple wasm32-unknown-wasi --build-path "$buildPath" -Xlinker -licuuc -Xlinker -licui18n`

the compilation finishes correctly, which leads me to believe you are just missing the flags when generating the bundle and dev commands.

**Comment by MaxDesiatov** [comment]
Thanks for the clarification, I'm waiting for CI to finish on a PR that fixes it, will tag a patch release with that shortly.

**Comment by Sefford** [comment]
Thanks!
