### ISSUE TITLE
carton 0.12.1 displays warnings

### ISSUE THREAD

**Issue by bluecpp** [swiftwasm/carton#274]
carton installed from brew runs into warnings or errors when issued. I see the version in the end. But there are other messages. Is this the normal behavior or is it an issue? I am not completely sure.

$ carton --version
objc[16139]: Class _TtC6Crypto18EllipticCurvePoint is implemented in both /usr/local/Cellar/carton/0.12.1/lib/libSwiftPMDataModel.dylib (0x1036f7ce0) and /usr/local/Cellar/carton/0.12.1/bin/carton (0x10102ff48). One of the two will be used. Which one is undefined.
objc[16139]: Class _TtC6Crypto27BoringSSLEllipticCurveGroup is implemented in both /usr/local/Cellar/carton/0.12.1/lib/libSwiftPMDataModel.dylib (0x1036f7da0) and /usr/local/Cellar/carton/0.12.1/bin/carton (0x101030008). One of the two will be used. Which one is undefined.
objc[16139]: Class _TtC6Crypto14ECDSASignature is implemented in both /usr/local/Cellar/carton/0.12.1/lib/libSwiftPMDataModel.dylib (0x1036f7e50) and /usr/local/Cellar/carton/0.12.1/bin/carton (0x1010300b8). One of the two will be used. Which one is undefined.
objc[16139]: Class _TtCV6Crypto25ArbitraryPrecisionInteger14BackingStorage is implemented in both /usr/local/Cellar/carton/0.12.1/lib/libSwiftPMDataModel.dylib (0x1036f7f50) and /usr/local/Cellar/carton/0.12.1/bin/carton (0x1010301b8). One of the two will be used. Which one is undefined.
objc[16139]: Class _TtC6Crypto28FiniteFieldArithmeticContext is implemented in both /usr/local/Cellar/carton/0.12.1/lib/libSwiftPMDataModel.dylib (0x1036f8018) and /usr/local/Cellar/carton/0.12.1/bin/carton (0x101030270). One of the two will be used. Which one is undefined.
**0.12.1**

**Comment by yonihemi** [comment]
Thank you for reporting. It appears carton installed from homebrew dumps duplicate warnings on every invocation.
We should fix it but it shouldn't stop you from using it meanwhile.

**Comment by bluecpp** [comment]
Thank you for your response. Yes it is usable, regardless of the messages.

**Comment by MaxDesiatov** [comment]
I'd start looking into possible static linking of `SwiftPMDataModel` if that's possible at all. I hope that would resolve it.
