### ISSUE TITLE
Error: This version of the operating system is not supported

### ISSUE THREAD

**Issue by darkoverlordofdata** [swiftwasm/carton#280]
uname:
Linux penguin 5.4.151-16908-gff376e5d5ee1 #1 SMP PREEMPT Sat Dec 11 19:42:45 PST 2021 aarch64 GNU/Linux
 
I'm running debian bullseye in kvm on my chromebook. Ubuntu 20.04 is based on bullseye.

I built from source.The only difference in the install is that I'm using binaryen v99,  because the install_ubuntu_deps.sh tries to install binaryen-version_97-x86_64, so for arm I am using the version in the repo, which is v99.

```
carton init --template tokamak --name frodo

Creating new project with template tokamak in frodo
- checking Swift compiler path: /home/darko/.carton/sdk/wasm-5.5.0-RELEASE/usr/bin/swift
- checking Swift compiler path: /home/darko/.swiftenv/versions/wasm-5.5.0-RELEASE/usr/bin/swift
Fetching release assets from https://api.github.com/repos/swiftwasm/swift/releases/tags/swift-wasm-5.5.0-RELEASE
Response contained body, parsing it now...
Error: This version of the operating system is not supported
```

**Comment by darkoverlordofdata** [comment]
I see the problem; in ToolchainManagement.swift, you check the contents of /etc/lsb-release. 
I removed that section and coded the ubuntu version as
  let ubuntuSuffix = "ubuntu20.04"
I generally have no problem importing ubuntu repo software into debian and other debian derivatives such as elementaryos.

So I recompiled carton, and I get The Swift version wasm-5.5.0-RELEASE was not found

Checking further, I am taken to https://github.com/swiftwasm/swift/releases/tag/swift-wasm-5.5.0-RELEASE and see the issue I cannot workaround:

```
 There is no aarch64 version for Ubuntu. 
```
Do you have plans to release an ARM64 version for Linux?

**Comment by MaxDesiatov** [comment]
We don't have firm plans for ARM64 Linux support. I'm not sure how compatible SwiftWasm is with this platform. This is also complicated by the fact that GitHub Actions does not provide any hosts for ARM64 for us to test with on CI.

As soon as ARM64 is available on GitHub Actions I'm ready to commit to supporting it. But until then we need to spend some time on provisioning CI hosts manually and keep them running, for which we didn't have capacity so far.

**Comment by darkoverlordofdata** [comment]
Doh! Now I get it. The readme at https://github.com/swiftwasm/swift seems to say there is an arm64 version, but that's a copy of the apple/swift repo, and refers to the native version of swift, not the wasm version.
