### ISSUE TITLE
Add support for Swift 5.6 package description format

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#285]
Starting with Swift 5.6 `swift package dump-package` outputs JSON in format that's incompatible with Swift 5.5 declarations. Ideally, we should be able to support both Swift 5.5 and 5.6 package description formats in `carton`.

**Comment by SDGGiesbrecht** [comment]
Is this something I can help with? It sounds like it is just a matter of adapting the decoding of `DumpedManifest` [here](https://github.com/swiftwasm/carton/blob/4ca0cdf939113ef1d1e585bdc630f462b7a625f1/Sources/SwiftToolchain/Manifest.swift#L74-L123) for changes to the encoding of `Manifest` [here](https://github.com/apple/swift-package-manager/blob/6647fa09d6042b29cbb115eecf6f292beb7f6837/Sources/PackageModel/Manifest.swift#L472-L496). Or am I missing something? (I am also not very familiar with your testing arrangement.)

**Comment by MaxDesiatov** [comment]
That's largely correct, but I personally would like 5.5 and earlier Swift versions to be supported as well. One possible approach would be to keep these as separate model types, say `DumpedManifest_v5_5` and `DumpedManifest_v5_6` and decode into these conditionally, based on the detected toolchain version.

**Comment by SDGGiesbrecht** [comment]
I will give it a shot. I am new to your code base though, and probably not as fast as someone more familiar with it. So if it is already on someone’s to‐do list, then feel free to race ahead and not wait for me.

**Comment by SDGGiesbrecht** [comment]
This is not as easy as I thought. For one, SwiftPM needs to be updated, because the `Manifest` type you are using is unable to represent everything dumped by 5.6. But some of its new component types are neither `Decodable` nor have public initializers. I think you need to roll you own `Manifest` type, but if you need it to interact with other SwiftPM APIs, then...
