### ISSUE TITLE
Detecting completion of Wasm module instantiation

### ISSUE THREAD

**Issue by mhavu** [swiftwasm/carton#290]
Is there a way to detect the completion of instantiation of a `carton` bundled WASM module from JavaScript? Can I `await` on something until all the initialization code has run?

**Comment by MaxDesiatov** [comment]
If you're referring to the Wasm JS API, [`WebAssembly.instantiateStreaming` call is async](https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API#streaming_the_webassembly_module) and you can freely `await` for it to complete. If you need to run some custom JS code after initialization, you'll have to supply your own `index.html` file that contains or loads your custom code. This can be done with the `--custom-index-page` option, [as described in the "Usage" section](https://github.com/swiftwasm/carton#usage).

Does that answer your question?

**Comment by mhavu** [comment]
Isn't the WASM module instantiated in the JS file `carton` adds into the `<head>` of the `index.html` file? I need something I can `await` on in my custom JS code to make sure this bundled JS file has got the WASM module up and running. It would indeed be convenient to use `WebAssembly.instantiateStreaming`, but does it mean I would need to bundle Wasmer, JavaScriptKit, etc. without the help of `carton`?

**Comment by MaxDesiatov** [comment]
With `--custom-index-page` you can create your own `index.html`, possibly modelling it after [the dynamically generated file that `carton` provides](https://github.com/swiftwasm/carton/blob/74a49c1aa8f148b6b14e35574e3412906402c309/Sources/CartonKit/Server/HTML.swift), loading you Wasm modules however you want. 

You don't need Wasmer at all, it's only used in `carton test` right now, and JavaScriptKit is served by `carton dev` on a fixed `/dev.js` path (or `bundle.js` for release builds generated by `carton bundle`), which your custom `index.html` can load just as well as the dynamically generated one.

**Comment by mhavu** [comment]
Up to this point, I had only looked at the JS files in the `entrypoint` directory in the GitHub repository. Now that I checked the JS files in the `.carton/static` directory on my computer, I saw something more complete and less human-readable. I will need to look into generating my own `bundle.js`.

**Comment by MaxDesiatov** [comment]
You may consider something like [rollup with this config](https://github.com/swiftwasm/JavaScriptKit/blob/main/Runtime/rollup.config.js) to which we switched in JSKit `main` recently.

**Comment by mhavu** [comment]
I finally got around to generating my own `bundle.js`. I first tried bundling [`carton/entrypoint/bundle.js`](https://github.com/swiftwasm/carton/blob/main/entrypoint/bundle.js) with rollup using this config:
```javascript
import { nodeResolve } from '@rollup/plugin-node-resolve'

export default {
  input: 'carton_entrypoint_bundle.js',
  output: {
    file: 'bundle.js',
    format: 'iife'
  },
  plugins: [
    nodeResolve()
  ]
}
```
This bundles `@wasmer/wasi`, `@wasmer/wasmfs`, and `javascript-kit-swift` as expected. However, loading the file in the browser gives me the following error message:

> TypeError: undefined is not an object (evaluating 'Q$1.wasi_new')

Is something still missing?

**Comment by MaxDesiatov** [comment]
Which version of `@wasmer/wasi` and `@wasmer/wasmfs` are you using? I remember they've released a major update recently, which we haven't tested yet and it could be incompatible and cause issues similar to this.

**Comment by MaxDesiatov** [comment]
In case you're using newer versions of those, I'd recommend pinning them this way in your `package.json`:

```
    "@wasmer/wasi": "^0.12.0",
    "@wasmer/wasmfs": "^0.12.0",
```

**Comment by mhavu** [comment]
Thanks! The `@wasmer/wasi` module was at 1.0.2. I downgraded it, and the error went away.

**Comment by MaxDesiatov** [comment]
Great! If your setup is open-source, I'd be happy to reference it somehow from this repository for posterity.

**Comment by mhavu** [comment]
The project is not open-source, but I will gladly share this part of it. Maybe I should write a blog post at some point.
