### ISSUE TITLE
Binary Naming Conflict

### ISSUE THREAD

**Issue by kuhl** [swiftwasm/carton#291]
Carton is already a Perl dependency manager on Linux. I would love to do the leg work of getting the app in aptitude. I've compiled and use Carton on my Ubuntu Server. I'd like to see others have the option of building a CI system on Ubuntu to deploy Tokamak on their sites.

Swiftlet isn't taken?

**Comment by MaxDesiatov** [comment]
I have no idea how packaging works on Ubuntu, but would it be possible to create a symlink from `swift-carton` to the real `carton` binary installed in some other folder non in `PATH` env? It would make sense to name the package that way too. AFAIR, Swift does this for its clang installation on some Linux distros by naming `swift-clang`, doesn't it?

**Comment by MaxDesiatov** [comment]
Another solution is to specify a conflict with the Perl package, as Mono people have done here https://github.com/mono/mono/issues/9056#issuecomment-532951039

**Comment by MaxDesiatov** [comment]
BTW, is it an established practice to maintain Linux distro packaging scripts in a separate repository as the main upstream repository? I wouldn't mind keeping the packaging scripts here if that's what you prefer and what is recommended in the Linux distro packaging world.

**Comment by kateinoigakukun** [comment]
carton is no longer a CLI command but a SwiftPM Plugin, so name conflict is no longer a problem.
