### ISSUE TITLE
Watcher doesn't see my changes (0.12.2)

### ISSUE THREAD

**Issue by gujor** [swiftwasm/carton#295]
Hi! I was (am) curious to try this out, but got stuck when the watcher didn't see my file changes.

What I did:
- Followed the install instruction on macOS using brew.
- Used tokamak template.
- Run carton dev, browser started with "Hello, world!".
- Felt this was a great experience so far! Good job!
- Edited and saved the hello message, but it didn't trigger a rebuild or any output from carton / watcher.
- Tried the above on both Big Sur and Monterey, same error.
- Tried previous releases, they worked!
- Started looking through issues, found: https://github.com/swiftwasm/carton/pull/283#issuecomment-1003705593
- Wrote this issue to report that the above mentioned problem still exists :)

**Comment by yonihemi** [comment]
Thanks for reporting.

**Comment by Jomy10** [comment]
I also have this issue.

When I quit the carton dev server using `⌃C`, I get the following output:

```bash
These paths have changed, rebuilding...
- /Users/jonaseveraert/Documents/projects/wasm-game/TokamakApp/Sources/TokamakApp
- /Users/jonaseveraert/Documents/projects/wasm-game/TokamakApp/Sources/TokamakApp
- /Users/jonaseveraert/Documents/projects/wasm-game/TokamakApp/Sources/TokamakApp
Compiling...
/Library/Developer/Toolchains/swift-wasm-5.5.0-RELEASE.xctoolchain/usr/bin/swift build -c debug --product TokamakApp --triple wasm32-unknown-wasi -Xlinker -licuuc -Xlinker -licui18n -Xlinker /Users/jonaseveraert/.carton/static/so_sanitizer.wasm -Xlinker --stack-first
```

Thought this might be useful?

To me it seems like it only rebuild the project when the dev server was quit?

Anyway, great work on making carton, as gujor said:
> Felt this was a great experience so far! Good job!

**Comment by aargar1** [comment]
I am having this problem too. Very annoyning; do you have any hack fixes for the short term?

**Comment by kateinoigakukun** [comment]
It seems this blocking operation violates the Swift Concurrency's assumption of no blocking in async function.
https://github.com/swiftwasm/carton/blob/409c78dd1430d2c2c86bedd6c78275ebb35a208d/Sources/CartonKit/Server/Server.swift#L232

This async task won't be executed due to the violation.
https://github.com/swiftwasm/carton/blob/409c78dd1430d2c2c86bedd6c78275ebb35a208d/Sources/CartonKit/Server/Server.swift#L178

Let me think a little bit more to fix it in a polite way
