### ISSUE TITLE
“carton test” fails to run as of 0.14.0

### ISSUE THREAD

**Issue by SDGGiesbrecht** [swiftwasm/carton#313]
```
$ carton test
Directory doesn't exist or contains outdated polyfills: /root/.carton/static
Polyfills archive successfully downloaded from https://github.com/swiftwasm/carton/releases/download/0.13.0/static.zip
Unpacking the archive: /root/.carton/static.zip
Entrypoint integrity verified: /root/.carton/static/test.js
- checking Swift compiler path: /root/.carton/sdk/wasm-5.6.0-RELEASE/usr/bin/swift
Inferring basic settings...
- swift executable: /root/.carton/sdk/wasm-5.6.0-RELEASE/usr/bin/swift
SwiftWasm Swift version 5.6 (swiftlang-5.6.0)
Target: x86_64-unknown-linux-gnu

Parsing package manifest:
[...]

Building the test bundle before running the test suite...
Compiling...
/root/.carton/sdk/wasm-5.6.0-RELEASE/usr/bin/swift build -c debug --product [...]Tests -Xswiftc -color-diagnostics --triple wasm32-unknown-wasi -Xswiftc -Xclang-linker -Xswiftc -mexec-model=reactor -Xlinker --export=main
[...]
Build complete! [...]

`swift` process finished successfully
`swift build` completed [...]

Running the test bundle with wasmer:
Running...
wasmer [...]/.build/wasm32-unknown-wasi/debug/[...]Tests.wasm

Process failed and produced following output: 
Error: Process failed with non-zero exit status and following output:
 and following error output:
error: failed to run `[...]/.build/wasm32-unknown-wasi/debug/[...]Tests.wasm`
╰─▶ 1: No export `_start` found in the module.
       Similar functions found: `main`, `_initialize`.
       Try with: wasmer [...]/.build/wasm32-unknown-wasi/debug/[...]Tests.wasm -i main
```

The two mismatches I notice in the log are:
- `-Xlinker --export=main` vs `No export  ̀_start ̀ found in the module.`
- polyfills are reported as coming from 0.13.0, despite the docker image being 0.14.0 and the default Swift resolving to 5.6.

Is there a way tell Carton to pass `-i main` as a workaround?

**Comment by MaxDesiatov** [comment]
> polyfills are reported as coming from 0.13.0, despite the docker image being 0.14.0 and the default Swift resolving to 5.6.

Polyfills are downloaded as assets attached to the previous release, 0.13.0 in this case. It doesn't mean that polyfills are supposed to be used only with 0.13.0. The version mismatch is an unfortunate hack for attaching pre-release assets somewhere before a new release is tagged, that "somewhere" is one of the previous releases. We have to make CI green before 0.14.0 is released, so have to attach these assets somewhere.

Maybe using a draft release for polyfill assets distribution would be less confusing, I'm not 100% sure how well that would work in practice. We'd have to know the exact version of a future release for sure upfront. Also, wouldn't draft releases create new git tags potentially for wrong commits?

**Comment by j-f1** [comment]
> Polyfills are downloaded as assets attached to the previous release, 0.13.0 in this case. It doesn't mean that polyfills are supposed to be used only with 0.13.0. The version mismatch is an unfortunate hack for attaching pre-release assets somewhere before a new release is tagged. We have to make CI green before 0.14.0 is released, that "somewhere" is one of the previous releases.
> 
> Maybe using a draft release for polyfill assets distribution would be less confusing, I'm not 100% sure how well that would work in practice. We'd have to know the exact version of a future release for sure upfront. Also, wouldn't draft releases create new git tags potentially for wrong commits?


Maybe they could be hosted in a `swiftwasm/carton-assets` repo (with a folder for each Carton version)?

**Comment by MaxDesiatov** [comment]
I'm not a fan of creating a separate repository for everything, maybe we could host them in `gh-pages` branch of this same repo, serving not from the repository, but from GH Pages CDN instead?

**Comment by j-f1** [comment]
That could work too!

**Comment by SDGGiesbrecht** [comment]
Thank you for addressing it so swiftly. (Pun intended.)
