### ISSUE TITLE
LinkError: import function javascript_kit:swjs_call_function_no_catch must be callable

### ISSUE THREAD

**Issue by gmondada** [swiftwasm/carton#318]
On mac, I run these commands:
```
mkdir toto
cd toto
carton init --template basic
carton dev
```
Which ends by launching Safari. On Safari console I get this error:

`LinkError: import function javascript_kit:swjs_call_function_no_catch must be callable`

carton version: 0.12.2
sdk version: wasm-5.5.0-RELEASE

Tested also with JavaScriptKit 0.14.0 (default is 0.12.0) but nothing changes.

**Comment by gmondada** [comment]
I'm trying to understand how `carton` collects javascript functions from swift packages like JavaScriptKit and makes them available as imports to `WebAssembly.instantiate()`. I guess webpack in in the loop, but is there any doc about this process?

**Comment by gmondada** [comment]
On Chrome, the error is:
```
LinkError: WebAssembly.instantiate(): Import #5 module="javascript_kit" function="swjs_call_function_no_catch" error: function import requires a callable
handleError @ dev.js:95
```

**Comment by MaxDesiatov** [comment]
Thanks for the report. This is not reproducible for me with the latest version of `carton`. Have you tried using 0.14.1?

**Comment by gmondada** [comment]
With carton 0.14.1, it works! Thanks.
