### ISSUE TITLE
Add static file support

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/carton#38]
This is a prerequisite for https://github.com/swiftwasm/Tokamak/pull/155. Ideally there would be support for using `Bundle` to get the URL for the static resources at runtime.

---

@MaxDesiatov:
> I think that both `carton` and Tokamak should support [SwiftPM resources](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md), the only obvious problem being that the `Bundle` type is declared in Foundation...

@j-f1:
> Could `carton` or something else implement the `Bundle` class itself?

@MaxDesiatov:
> It probably could, but I'm not sure whether SwiftPM assumes a specific `Bundle` implementation in its code and whether we could swap that with our own. Needs some testing and research... 🧪

**Comment by MaxDesiatov** [comment]
I've tried to add a resources to `Package.swift` in our [todo example project](https://github.com/TokamakUI/tokamak-todo-example/stargazers):

```swift
  targets: [
    .target(
      name: "tokamak-todo-example",
      dependencies: [
        .product(name: "TokamakShim", package: "Tokamak"),
      ],
      resources: [
        .copy("tokamak_logo.png"),
      ]
    ),
  ]
```

Turns out SwiftPM generates a new file for the resource, which looks like this:

```swift
import class Foundation.Bundle

extension Foundation.Bundle {
    static var module: Bundle = {
        let bundlePath = Bundle.main.bundlePath + "/" + "tokamak-todo-example_tokamak-todo-example.resources"
        guard let bundle = Bundle(path: bundlePath) else {
            fatalError("could not load resource bundle: \(bundlePath)")
        }
        return bundle
    }()
}
```

It obviously fails to build because SwiftWasm Foundation doesn't have the `Bundle` in it, because underlying `CFBundle` relies on the streams implementation, which as far as I remember requires multi-threading. I think I can get a stub `Bundle` implementation, or maybe it's time to get streams working properly...

**Comment by MaxDesiatov** [comment]
Despite the compilation failure, the resource file is nevertheless copied to `.build/wasm32-unknown-wasi/debug/tokamak-todo-example_tokamak-todo-example.resources/tokamak_logo.png`, as the Swift snipet above correctly points to.

**Comment by MaxDesiatov** [comment]
I've added a basic `Bundle` implementation in https://github.com/swiftwasm/swift-corelibs-foundation/commit/40138b0e72bfb9643fbd4351d034f7fbbf7297b3, it will end up in the next 5.3 snapshot built off https://github.com/swiftwasm/swift/pull/1643 after that PR is merged (tomorrow I guess).

**Comment by MaxDesiatov** [comment]
I've made a stupid mistake in my `Bundle` implementation, which I fixed in https://github.com/swiftwasm/swift-corelibs-foundation/commit/ad9f20d160b97dbb0522ee762aa26b47eaf38510. We had some issues with snapshot distribution uploads, but these should be fixed today, and I'm keeping an eye on it.
