### ISSUE TITLE
`brew install swiftwasm/tap/carton` installs old version

### ISSUE THREAD

**Issue by gregcotten** [swiftwasm/carton#387]
On macOS 13 on Apple Silicon, running

`brew info swiftwasm/tap/carton`

results in the incorrect version (0.16.0). `brew install` installs the wrong version as well.

```
==> swiftwasm/tap/carton: stable 0.16.0 (bottled), HEAD
📦 Watcher, bundler, and test runner for your SwiftWasm apps
https://carton.dev
Not installed
From: https://github.com/swiftwasm/homebrew-tap/blob/HEAD/carton.rb
==> Dependencies
Required: binaryen ✔, wasmer ✔
==> Requirements
Required: Xcode >= 13.2.1 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 31 (30 days), 95 (90 days), 358 (365 days)
install-on-request: 31 (30 days), 95 (90 days), 357 (365 days)
build-error: 0 (30 days)
```

**Comment by carson-katri** [comment]
Not sure if this will help, but you may want to run `brew update` to get latest package definitions.

**Comment by gregcotten** [comment]
@carson-katri - no dice!

**Comment by gregcotten** [comment]
Fixed by running:
`brew untap swiftwasm/tap`
`brew tap swiftwasm/tap`
`brew install swiftwasm/tap/carton`

**Comment by filip-sakel** [comment]
Could this stay open? I've been trying to figure out how to fix incompatibility issues for _hours_.
