### ISSUE TITLE
compiler error, [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by carlhung** [swiftwasm/carton#391]
I tried to create my own docker image. because the current Carton docker doesn't have lldb debugger and soucekip-lsp. So, I tried to create my own. 
But when i typed:
```
$ swift build -c release
```
I got the following error:
```
/app/.build/checkouts/swift-tools-support-core/Sources/TSCclibc/process.c:10:12: error: call to undeclared function 'posix_spawn_file_actions_addchdir_np'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    return posix_spawn_file_actions_addchdir_np(file_actions, path);
           ^
/app/.build/checkouts/swift-tools-support-core/Sources/TSCclibc/process.c:10:12: note: did you mean 'SPM_posix_spawn_file_actions_addchdir_np'?
/app/.build/checkouts/swift-tools-support-core/Sources/TSCclibc/process.c:7:5: note: 'SPM_posix_spawn_file_actions_addchdir_np' declared here
int SPM_posix_spawn_file_actions_addchdir_np(posix_spawn_file_actions_t *restrict file_actions, const char *restrict path) {
    ^
1 error generated.
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
[8/882] Compiling a_object.c
```

To show my linux version with command, `uname -a`
```
Linux 94c915263026 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
swift's version:
```
Swift version 5.8 (swift-5.8-RELEASE)
Target: x86_64-unknown-linux-gnu
```
my clang version with command, `clang --version`
```
clang version 13.0.0 (https://github.com/apple/llvm-project.git f0fb631dd1a3a2988b23ba5057cd9106713cd0b4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by Soutaisei** [comment]
Can confirm I have the same issue on PopOS (which is based on Ubuntu) when trying to build with the _install_ubuntu_deps.sh_

**Comment by kateinoigakukun** [comment]
Thank you for your reports. It will be resolved by https://github.com/apple/swift-tools-support-core/pull/363, which will be included in the next carton release. So just a moment, please :pray:

**Comment by Soutaisei** [comment]
Can confirm that I no longer have the error after the update.
Built and runs fine on Swift 5.8

**Comment by carlhung** [comment]
Ok. But does it work? I mean, have you tried to run the sample code and see something on the browser?

**Comment by Its-Kenta** [comment]
Also yes.

**Comment by Soutaisei** [comment]
> Ok. But does it work? I mean, have you tried to run the sample code and see something on the browser?

Correct. I've tested it and it works fine.
Tried it on two linux machines with different distros.
