### ISSUE TITLE
Implement `carton test` command

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#42]
This should build tests, passing the resulting binary to a test runner after that. This could be implemented in a few separate steps:

- [x] use [`wasmer`](https://wasmer.io/) as a basic CLI test runner;
- [x] use the `--enable-test-discovery` flag to inject the JSON test observer so that test reports can be parsed (blocked by the lack of `libIndexStore.dylib` in recent snapshots);
- [ ] ~consider using Node.js as another CLI runner option?~ Tracked separately in https://github.com/swiftwasm/carton/issues/174
- [ ] host the test bundle via HTTP on localhost with a browser loading an appropriate entrypoint, running the tests and reporting test results back to the HTTP server;
- [ ] ~make `wasmer` an optional dependency.~ Tracked separately in #177

There's a question of how the target environment is selected. The `wasmer` option is what will be implemented first, and probably will be the default, but when browser environments are supported, should `carton test` launch tests in parallel in all possible environments? What should the appropriate option name be for selecting a specific test runner? `--target` (as in "the target environment"), `--host` (as in "the webassembly host"), `--environment` (probably the most unambiguous), `--runner`? I'm currently thinking of `--environment`, but all feedback is welcome as usual.

**Comment by thecb4** [comment]
@MaxDesiatov a couple of questions on this. When we test. We're running a JS Script that tests against the wasm file. Is there any way to mimic UITests and reference "IDs" or names generated in the HTML? If there is a way for introspection and use by the test harness, then we shouldn't care about a browser. We could use pure swift, and test browsers as a secondary effort.

**Comment by MaxDesiatov** [comment]
Unfortunately, I don't think that's possible without parsing that HTML and maybe even having a complete DOM environment with WebAssembly support. I reckon that in some way it would be an effort comparable to maintaining our own small browser engine. I may be wrong and I'm happy to consider any viable options though.
