### ISSUE TITLE
Verify SDK is already installed before installing the same version

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#45]
The behavior of installing an SDK with the same exact version as already installed is currently not handled properly.

**Comment by RayZhao1998** [comment]
What's the meaning of this? I've tried to install the version already installed, I think it's working well. 

```
carton sdk install wasm-DEVELOPMENT-SNAPSHOT-2020-07-02-a
Inferring basic settings...
- swift executable: /Users/ziyuanzhao/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-07-02-a/usr/bin/swift
Swift version 5.3-dev (LLVM c5b1848323200a8, Swift 66efa1272c2973b)
Target: x86_64-apple-darwin19.5.0
```

**Comment by MaxDesiatov** [comment]
Thanks for checking! I was looking at the code and thought it would reinstall it from scratch. I'll have another look at the code probably close this.

**Comment by RayZhao1998** [comment]
Yep. I think the function [`checkAndLog`](https://github.com/swiftwasm/carton/blob/749a17d7308f3eeee4d58ec0dd47bb544458d84c/Sources/SwiftToolchain/ToolchainManagement.swift#L96) in `ToolchainManagement.swift` will check the specific version whether exists.
