### ISSUE TITLE
Print the error output of `swift package dump-package`

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#78]
Currently when `swift package dump-package` fails, its error output is not presented to the user, while the printed error message is confusing. In 0.4.1 it's 
```
Error: No package found
```
while in `main` it's 
```
Error: The `Package.swift` manifest file could not be found. Please
navigate to a directory that contains `Package.swift` and restart
```

Neither of these are valid error messages when `Package.swift` is present, but it has a typo or doesn't compile for some other reason.

**Comment by smic** [comment]
I followed the instructions with MacOS 11 and Xcode 12 Beta 4 and got the same error. If try to execute the command, then I get following output:

$ /Users/stephan/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/bin/swift package dump-package
/Users/stephan/Documents/Projects/TokamakApp: error: manifest parse error(s):
<unknown>:0: error: invalid Darwin version number: macos11.0
<unknown>:0: error: invalid version number in '-target x86_64-apple-macos11.0'
/Applications/Xcode12-beta4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Combine.framework/Modules/Combine.swiftmodule/x86_64-apple-macos.swiftinterface:1:1: error: failed to build module 'Combine' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.2.24.2 clang-1200.0.27.70)', may have used features that aren't supported by this compiler, 'Swift version 5.3-dev (LLVM b54b6b832e, Swift 4bb1458ec4)'
// swift-interface-format-version: 1.0
^
<unknown>:0: error: invalid Darwin version number: macos11.0
<unknown>:0: error: invalid version number in '-target x86_64-apple-macos11.0'

**Comment by MaxDesiatov** [comment]
Thanks reporting this. Unfortunately, as specified in [the "Requirements" section](https://github.com/swiftwasm/carton#requirements), Xcode 12 betas are not currently supported due to the bugs we see in those versions. We're waiting for those to be fixed in later beta or release versions and will apply workarounds if it's not fixed in Xcode 12 GM.

In the meantime, would you be able to use Xcode 11? Xcode 11.6 is well tested and worked for me on Catalina. I didn't test it on Big Sur as I don't have access to hardware for testing, but I'd expect it works there as well.

**Comment by smic** [comment]
I installed Xcode 11. Yes, it doesn't report this error with Xcode.app 11. Unfortunately it has now other problems:

[...]
[302/306] Compiling TokamakDOM DOMRenderer.swift
[306/309] Compiling TokamakApp main.swift
/Users/stephan/Documents/Projects/TokamakApp/Sources/TokamakApp/main.swift:9:16: error: cannot find 'DOMRenderer' in scope
let renderer = DOMRenderer(ContentView(), div)
[307/309] Compiling TokamakApp ContentView.swift
Process failed, check the build process output above.

**Comment by carson-katri** [comment]
The template app needs to be updated. We only support the `App` protocol as the entrypoint now:

```swift
struct MyApp: App {
  var body: some Scene {
    WindowGroup("My App") { ... }
  }
}
```

**Comment by MaxDesiatov** [comment]
Apologies, that's a change in the public API of Tokamak which broke the template in `carton`. 

You can change `main.swift` in the generated template to the new `App` lifecycle:

```swift
import TokamakShim

struct Counter: View {
  @State var count: Int
  let limit: Int

  var body: some View {
    if count < limit {
      VStack {
        Button("Increment") { count += 1 }
        Text("\(count)")
      }
      .onAppear { print("Counter.VStack onAppear") }
      .onDisappear { print("Counter.VStack onDisappear") }
    } else {
      VStack { Text("Limit exceeded") }
    }
  }
}

struct CounterApp: App {
  var body: some Scene {
    WindowGroup("Counter Demo") {
      Counter(count: 5, limit: 15)
    }
  }
}

// @main attribute is not supported in SwiftPM apps.
// See https://bugs.swift.org/browse/SR-12683 for more details.
CounterApp.main()
```

We weren't able to restrict Tokamak dependencies in templates to a specific version due to the use of unsafe flags https://github.com/swiftwasm/JavaScriptKit/issues/6. Unfortunately, SwiftPM forbids depending on specific versions when unsafe flags are used. A workaround for that is available in latest SwiftWasm snapshots and we're working hard on making the onboarding experience more smooth in next `carton` and Tokamak versions that are going to be published soon.
