### ISSUE TITLE
Compiling swift packages that depend on Darwin or Glibc

### ISSUE THREAD

**Issue by mathieutozer** [swiftwasm/carton#89]
I'm toying with this project to bear with me.

Trying to compile SwiftDate as a dependency

The following https://github.com/basvankuijck/SwiftDate/blob/master/Sources/SwiftDate/Formatters/RelativeFormatter/RelativeFormatter%2BStyle.swift fails as Darwin doesn't exist of course.

I guess my question is - is this going to be possible? I am guessing some Darwin / Glibc or equivalent might exist so I can use this library?

**Comment by mathieutozer** [comment]
I think this question might belong with Tokamak instead...

**Comment by carson-katri** [comment]
I'd fork it and replace all `#if os(Linux)` with `#if os(Linux) || os(WASI)` as a first step.

**Comment by MaxDesiatov** [comment]
This issue does belong to SwiftWasm in general, I'm not sure it is specific to either Tokamak or `carton`. As Carson mentioned, `import Glibc` will work, and you can check for it with `os(WASI)`. Bear in mind that WASI libc is not 100% compatible with Glibc and in the near future we'll rename that module to `WASI` to indicate that, so you'll have to use `import WASI` instead with future SwiftWasm snapshots. But for now `import Glibc` should work.

Does that resolve your issue?

**Comment by mathieutozer** [comment]
Where can I confirm that `WASI` is being defined?  Adding `os(WASI)` still seems to cause the compiler to try to compile for the Apple platforms

**Comment by MaxDesiatov** [comment]
This depends on the build invocation you use. If you build with `carton dev`, it always builds for WASI/WebAssembly and `#if os(WASI)` conditions are evaluated then. Could you clarify please how exactly do you build your project for WebAssembly?

**Comment by mathieutozer** [comment]
I'm using carton 

```
tozer@Mathieus-iMac Barnes % carton --version
0.4.1
tozer@Mathieus-iMac Barnes % swiftenv version
wasm-5.3-SNAPSHOT-2020-08-15-a (set by /Users/tozer/.swiftenv/version)


tozer@Mathieus-iMac Barnes % carton dev
Polyfill integrity verified: /Users/tozer/.carton/static/dev.js
Inferring basic settings...
- swift executable: /Users/tozer/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/bin/swift
Swift version 5.3-dev (LLVM b54b6b832e, Swift 4bb1458ec4)
Target: x86_64-apple-darwin19.6.0

Parsing package manifest: /Users/tozer/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/bin/swift package dump-package
- development binary to serve: /Users/tozer/code/SwiftDate/Barnes/.build/wasm32-unknown-wasi/debug/Barnes

Building the project before spinning up a server...
/Users/tozer/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/bin/swift build -c debug --product Barnes --enable-test-discovery --destination /Users/tozer/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a.json
[4/4] Linking Barnes
Process completed successfully

Parsing package manifest: /Users/tozer/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/bin/swift package dump-package

Watching these directories for changes:
/Users/tozer/code/SwiftDate/Barnes/Sources/Barnes

[ NOTICE ] Server starting on http://127.0.0.1:8080
```

**Comment by MaxDesiatov** [comment]
Thanks for sharing that, the output seems valid to me, thus `os(WASI)` conditions should be evaluated correctly in this setting. You can check out [the source code of the `TokamakShim` module](https://github.com/swiftwasm/Tokamak/blob/main/Sources/TokamakShim/TokamakShim.swift) which uses similar conditions as an example.

**Comment by MaxDesiatov** [comment]
I've tried to compile SwiftDate on my side, but it doesn't look like the library will work as is. It depends on things that aren't available in WebAssembly such as multi-threading, as SwiftDate relies on `Foundation` APIs such as `Thread.current`. Similarly, it expects locale and time zone files to exist, but these aren't currently supplied by browsers, or there's no corresponding JavaScript API for it.

The only workaround I currently see is bridging to JavaScript and using something like [moment.js](https://momentjs.com/), which does supply its own locale and time zone information. Otherwise a similar library has to be built for SwiftWasm.

**Comment by MaxDesiatov** [comment]
If you see issues in compiling anything other than SwiftDate, please feel free [to open an issue in the main SwiftWasm repository](https://github.com/swiftwasm/swift/issues) or to reopen this one. Thanks again for raising this!

**Comment by mathieutozer** [comment]
Thanks for trying it out - I was really just seeing how far I could get, so that has saved me some time. Perhaps I'll try with some even leaner libraries like https://github.com/pointfreeco/swift-prelude

**Comment by MaxDesiatov** [comment]
BTW, the time zones issue is tracked in https://github.com/swiftwasm/swift/issues/1148, and the wider Foundation status in https://github.com/swiftwasm/swift/issues/592#issuecomment-659480405. Libraries that don't rely on Dispatch and filesystem APIs should work or be easily adaptable for SwiftWasm. And we do want to enable both FS and Dispatch in the future, but these are complex tasks and we had a few other things on our roadmap to resolve before that.

**Comment by mathieutozer** [comment]
I understand the considerable work to make this all happen! 

While I've got you - is there a list somewhere of the status of 1st and 3rd party (from an application engineering standpoint) libraries?

**Comment by MaxDesiatov** [comment]
The only list I know of is [awesome-swiftwasm](https://github.com/swiftwasm/awesome-swiftwasm), and the only actively maintained seem to be [JavaScriptKit](https://github.com/swiftwasm/JavaScriptKit) and [Tokamak](https://tokamak.dev). The latter also depends on my forks of [Runtime](https://github.com/MaxDesiatov/Runtime) and [OpenCombine](https://github.com/MaxDesiatov/OpenCombine), and I plan to submit those changes to their upstream repositories at some point.

If you find anything else or maintain something yourself, please feel free to submit a PR to the [awesome-swiftwasm](https://github.com/swiftwasm/awesome-swiftwasm) list. The ecosystem is in its early stage, and all help we can get is much appreciated 🙏

Maybe the only thing missing here is XCTest, a subset of which is also supported (expectation and `Bundle` APIs are unavailable), and you can run `carton test` in your package to get simple test suites running. I'll update `carton`'s `README.md` tomorrow to reflect that.

**Comment by mathieutozer** [comment]
Turns out I don't know How To Swift Package Manger - I wasn't updating my locally patched packages with 
`swift package update`
