### ISSUE TITLE
Error: could not find executable 

### ISSUE THREAD

**Issue by spprichard** [swiftwasm/carton#9]
I'm trying to get the demo for Tokamak, which has me install carton. I believe I have done that properly. 
I then cloned this repo, then from the project root I run `carton dev --product Tokamak` This leads to the following error 
```
(base) ➜  Tokamak git:(main) ✗ carton dev --product TokamakDemo
Polyfill integrity verified: /Users/stevenprichard/.carton/static/dev.js
Inferring basic settings...
- swift executable: /Users/stevenprichard/.swiftenv/versions/5.2.4/usr/bin/swift
Parsing package manifest: /Users/stevenprichard/.swiftenv/versions/5.2.4/usr/bin/swift package dump-package
Error: could not find executable for '/Users/stevenprichard/.swiftenv/versions/5.2.4/usr/bin/swift'
```

There appears to be nothing in my `~/.swiftenv/versions` 
Checking my swift version...
```
(base) ➜  Tokamak git:(main) ✗ swift --version
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.5.0
```

Attempting to check the version of swift swiftenv is using....
```
(base) ➜  Tokamak git:(main) ✗ swiftenv which swift
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
```

swiftenv looks like it can see the local swift version...
```
(base) ➜  Tokamak git:(main) ✗ swiftenv local
5.2.4
```

Not sure if all this context is needed, just kinda at a lost. Given the error I am getting from 
`carton dev --product TokamakDemo` it doesn't appear like things are messing. Might be my environment/machine? 
Any thoughts?

**Comment by MaxDesiatov** [comment]
Hi @spprichard, sorry for the inconvenience, the error messages could be much better and I'll improve those ASAP. In the meantime due to #3, you have to install the toolchain manually with `swiftenv` as described in [the SwiftWasm book](https://swiftwasm.github.io/swiftwasm-book/index.html#getting-started-with-nightly-toolchain). At least from your description it looks like it isn't installed.

**Comment by spprichard** [comment]
Thank you for the quick reply!

Alright, I'll try that. I think the reason I missed that is the link in the README is broken. I am getting a 404
![image](https://user-images.githubusercontent.com/10872240/85405967-b9deea00-b526-11ea-92ff-00019cb7816b.png)

Again, I appreciate your help! Super excited to try this out!!

**Comment by MaxDesiatov** [comment]
Apologies, and many thanks for reporting the issue! The link in `README.md` is fixed now and I'm working on automatic toolchain installation support in `carton` as we speak. I'm happy that you're trying SwiftWasm and Tokamak, please feel free to submit any feedback 🙂

**Comment by MaxDesiatov** [comment]
In the meantime, I'll keep the issue open until #3 is resolved.

**Comment by spprichard** [comment]
Sounds good. Once I made the changes you suggested, I was able to get the Tokamak demo working!!

**Comment by MaxDesiatov** [comment]
`carton` 0.2.0 has been released, which is now automatically installs SwiftWasm if needed, `swiftenv` no longer required.
