### ISSUE TITLE
Allow templates to be downloaded from remote repositories

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#91]
This would allow users to create their own templates, but also would allow us to fix templates quickly without forcing our users to update `carton` on their side.

**Comment by MaxDesiatov** [comment]
I've created [a basic template repository](https://github.com/swiftwasm/browser-basic-template), which also has a textual introduction with links for beginners, and a working test suite.

**Comment by j-f1** [comment]
Perhaps this could be implemented like Homebrew taps? `user/name` would download `https://github.com/user/carton-template-name/archive/main.zip`, with `user` defaulting to `swiftwasm` if not provided. Alternately, users could pass a full URL to a zip or tgz file that would be unpacked.

**Comment by MaxDesiatov** [comment]
Yes, totally! 👍 I think we'd keep `basic` and `tokamak` as aliases for two corresponding repositories, but would be great to support what you've described as a general form.
